# Generated by Django 4.2.8 on 2023-12-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('resume', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('P', 'Paseo'), ('C', 'Cuidado'), ('A', 'Alojamiento')], max_length=1)),
            ],
            options={
                'db_table': 'walkers_db',
            },
        ),
    ]
